[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python -m gunicorn backend.wsgi:application" 