[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && python -m ensurepip --upgrade", "cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python -m gunicorn backend.wsgi:application" 