# Generated by Django 5.0.1 on 2025-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional comments from student for registration officer', null=True),
        ),
    ]
