# Generated by Django 5.0.1 on 2025-07-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_name', models.CharField(help_text='Name to display with signature', max_length=255)),
                ('signature_title', models.CharField(help_text='Title/role of the signatory', max_length=255)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='registration.registration')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('registration', 'signed_by')},
            },
        ),
    ]
