# Generated by Django 5.0.1 on 2025-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_registered_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='Software Engineering', max_length=100),
        ),
    ]
