# Generated by Django 5.0.1 on 2025-06-25 16:57

from django.db import migrations, models
import django.db.models.deletion

def create_department(apps, schema_editor):
    Department = apps.get_model('courses', 'Department')
    Department.objects.get_or_create(code='SEN', name='Software Engineering')

class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0006_alter_course_options_alter_courseallocation_options_and_more'),
        ('users', '0004_alter_user_department'),
    ]

    operations = [
        migrations.RunPython(create_department),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department_fk',
            field=models.ForeignKey('courses.Department', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students'),
        ),
    ]
