# Generated by Django 5.0.1 on 2025-06-25 16:57

from django.db import migrations

def update_department_fk(apps, schema_editor):
    Department = apps.get_model('courses', 'Department')
    User = apps.get_model('users', 'User')
    dept = Department.objects.get(code='SEN')
    User.objects.filter(department='Software Engineering').update(department_fk=dept)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250625_1757'),
    ]

    operations = [
        migrations.RunPython(update_department_fk),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department_fk',
            new_name='department',
        ),
    ]
