# Generated by Django 5.0.1 on 2025-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature for admin users', null=True, upload_to='signatures/'),
        ),
    ]
