# Generated by Django 5.0.1 on 2025-06-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.department'),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course', 'department', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'department')},
        ),
    ]
