# Generated by Django 5.0.1 on 2025-06-24 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='registered_students',
            field=models.ManyToManyField(blank=True, related_name='registered_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
