# Generated by Django 5.0.1 on 2025-06-25 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='max_capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='registered_students',
            field=models.ManyToManyField(blank=True, related_name='allocated_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='session',
        ),
    ]
