# Generated by Django 5.0.1 on 2025-06-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together=set(),
        ),
    ]
