# Generated by Django 5.0.1 on 2025-06-25 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseallocation_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='courseallocation',
            options={'ordering': ['course__code']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], default=2),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='registered_students',
            field=models.ManyToManyField(related_name='allocated_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
