# Generated by Django 5.0.1 on 2025-06-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_courseallocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseallocations', to='courses.course'),
        ),
    ]
