# Generated by Django 5.0.1 on 2025-06-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_department_hod_academicsession_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='courses.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course', 'session')},
        ),
    ]
