# Generated by Django 5.0.1 on 2025-06-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseallocation_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='courses.academicsession'),
        ),
    ]
