# Generated by Django 5.0.1 on 2025-06-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseallocation_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Course Registration Deadline', max_length=200)),
                ('description', models.TextField(default='Register your courses before the deadline expires.')),
                ('late_fee_message', models.TextField(default='Late Registration attracts the payment of ₦5000 naira only. If you fail to register your courses online, your semester registration will be void.')),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('allow_late_registration', models.BooleanField(default=True)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_deadlines', to='courses.academicsession')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
