# Generated by Django 5.0.1 on 2025-07-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_registrationdeadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationDeadline',
        ),
    ]
